### ISSUE TITLE
can't run your demo  / bin setup doesn't work

### ISSUE THREAD

**Issue by asedel** [oddballio/rails-with-react#2]
edelBook:SourceCode asedelst$ rbenv install 2.5.3
rbenv: /Users/asedelst/.rbenv/versions/2.5.3 already exists
continue with installation? (y/N) n
edelBook:SourceCode asedelst$ git clone git@github.com:oddballio/rails-with-react.git
Cloning into 'rails-with-react'...
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 129 (delta 0), reused 0 (delta 0), pack-reused 126
Receiving objects: 100% (129/129), 91.32 KiB | 2.69 MiB/s, done.
Resolving deltas: 100% (11/11), done.
edelBook:SourceCode asedelst$ cd rails-with-react/
edelBook:rails-with-react asedelst$ ./bin/setup 
== Installing dependencies ==
Successfully installed bundler-2.0.2
Parsing documentation for bundler-2.0.2
Done installing documentation for bundler after 3 seconds
1 gem installed
Traceback (most recent call last):
	2: from /Users/asedelst/.rbenv/versions/2.5.3/bin/bundle:23:in `<main>'
	1: from /Users/asedelst/.rbenv/versions/2.5.3/lib/ruby/2.5.0/rubygems.rb:308:in `activate_bin_path'
/Users/asedelst/.rbenv/versions/2.5.3/lib/ruby/2.5.0/rubygems.rb:289:in `find_spec_for_exe': can't find gem bundler (>= 0.a) with executable bundle (Gem::GemNotFoundException)
Traceback (most recent call last):
	2: from /Users/asedelst/.rbenv/versions/2.5.3/bin/bundle:23:in `<main>'
	1: from /Users/asedelst/.rbenv/versions/2.5.3/lib/ruby/2.5.0/rubygems.rb:308:in `activate_bin_path'
/Users/asedelst/.rbenv/versions/2.5.3/lib/ruby/2.5.0/rubygems.rb:289:in `find_spec_for_exe': can't find gem bundler (>= 0.a) with executable bundle (Gem::GemNotFoundException)

== Command ["bundle install"] failed ==
edelBook:rails-with-react asedelst$ ruby -v
ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-darwin18]

**Comment by RobAWilkinson** [comment]
it looks like bundle isnt installed correctly, can you try `gem install bundler` and then `bundle install`? @asedel

**Comment by asedel** [comment]
edelBook:rails-with-react asedelst$ gem install bundler
Successfully installed bundler-2.0.2
Parsing documentation for bundler-2.0.2
Done installing documentation for bundler after 3 seconds
1 gem installed
edelBook:rails-with-react asedelst$ bundler install
Traceback (most recent call last):
	2: from /Users/asedelst/.rbenv/versions/2.5.3/bin/bundler:23:in `<main>'
	1: from /Users/asedelst/.rbenv/versions/2.5.3/lib/ruby/2.5.0/rubygems.rb:308:in `activate_bin_path'
/Users/asedelst/.rbenv/versions/2.5.3/lib/ruby/2.5.0/rubygems.rb:289:in `find_spec_for_exe': can't find gem bundler (>= 0.a) with executable bundler (Gem::GemNotFoundException)
